# Generated by Django 4.0.3 on 2022-03-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_signinform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupform',
            old_name='id_name',
            new_name='first_name',
        ),
    ]
