# Generated by Django 4.0.3 on 2022-03-29 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_rename_id_name_signupform_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupform',
            old_name='first_name',
            new_name='name',
        ),
    ]
