# Generated by Django 4.0.3 on 2022-03-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_rename_first_name_signupform_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SigninForm',
        ),
        migrations.DeleteModel(
            name='SignupForm',
        ),
    ]
